package com.gordon.rawe.models;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.gordon.rawe.models.Person;
import com.gordon.rawe.models.News;

import com.gordon.rawe.models.PersonDao;
import com.gordon.rawe.models.NewsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personDaoConfig;
    private final DaoConfig newsDaoConfig;

    private final PersonDao personDao;
    private final NewsDao newsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        newsDaoConfig = daoConfigMap.get(NewsDao.class).clone();
        newsDaoConfig.initIdentityScope(type);

        personDao = new PersonDao(personDaoConfig, this);
        newsDao = new NewsDao(newsDaoConfig, this);

        registerDao(Person.class, personDao);
        registerDao(News.class, newsDao);
    }
    
    public void clear() {
        personDaoConfig.getIdentityScope().clear();
        newsDaoConfig.getIdentityScope().clear();
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public NewsDao getNewsDao() {
        return newsDao;
    }

}
